### ISSUE TITLE
Implement ros2bag as part of new ros2cli verb

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#2]
Connects to ros2/ros2#533

Envisioned verb configurations

- [x] `add ros2 bag *` as a new verb: see https://github.com/ros2/rosbag2/pull/7
- [x] `ros2 bag record [-a | topic1 [topic2 ... topicN]`: see https://github.com/ros2/rosbag2/issues/13
- [x] `ros2 bag play <file_to_bag>`: see https://github.com/ros2/rosbag2/issues/14
- [x] `ros2 bag info <file_to_bag>`: see https://github.com/ros2/rosbag2/issues/15
