### ISSUE TITLE
Implement ros2 agnostic storage API

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#4]
Connects to ros2/ros2#533

The storage API shall be ROS 2 agnostic and only handles the file access to read and write serialized binary code. It shall be able to describe the binary data with enough meta information to restore a complete message out of it.

Todos:
- [x] implement abstract storage API interface: see https://github.com/ros2/rosbag2/issues/8
- [x] factory loading the storage plugin to work with: see https://github.com/ros2/rosbag2/pull/7
- [x] feature a SQLite3 plugin: see https://github.com/ros2/rosbag2/issues/9
- [x] feature a ROS 1 bag plugin: see https://github.com/ros2/rosbag2/issues/10
