### ISSUE TITLE
Performance testing of rosbag2

### ISSUE THREAD

**Issue by adamdbrw** [ros2/rosbag2#435]
Rosbag2 is currently not optimized for performance and requires some work to get to where user needs are. See #123, or [this article](https://medium.com/@nbelakovski/how-to-use-rti-recording-service-with-ros2-9e57d486b38c).

Tasks:
1. [X] create a branch with a comprehensive testing/benchmarking package --> WIP merge request #442 
2. [X] run tests for representative use-cases and share plotted results (results are published, see comments).
3. [X] identify the performance bottleneck - disk I/O, especially sqlite transaction, waiting for completed writes. See [comment below](https://github.com/ros2/rosbag2/issues/435#issuecomment-642212788).
4. [X] describe & quantify effects of various parameters (sqlite journal, sync pragmas, transaction size etc.) on performance
5. [X] raise issues for improvements
6. [X] Resolve WIP status for #442, refactoring code, fixing issues and bringing it up quality ready for a review. 
7. [X] Isolate recorder performance from transport issues - benchmark on stack messages (as if already received in callback.
8. [X] Run Voyager use-case with different parameters and different sqlite settings to compare with baseline and see how much improvement there is ==> subtask 2.
9. [X] Post the findings of how far performance can be improved (using hacky methods to change some parameters that are hardcoded/unchangeble now - e.g. configuration of sqlite #437).
10. [X] Present results on Tooling WG rosbag2 performance breakout session

Ongoing action items:
1. [x] Go through review process of #442

**Comment by emersonknapp** [comment]
These are really great findings! I'd love it if we could put some graphs/numbers on these findings so that we can make data-driven decisions on how to prioritize improvements. 
I see that you have on your checklist "share plotted results" and "quantify effects of various parameters" - so it sounds like you're already planning to do this.

**Comment by adamdbrw** [comment]
Yes, this is planned - I will be posting updates to issues and #442 merge request. Most of parts are in place, but making them work together and reliably needs some time still

**Comment by dejanpan** [comment]
@adamdbrw reproducer for this [article](https://medium.com/@nbelakovski/how-to-use-rti-recording-service-with-ros2-9e57d486b38c) : https://github.com/ros2/rosbag2/issues/354.

**Comment by adamdbrw** [comment]
Following a presentation on today's Tooling WG, I will share results (summaries and raw input). With the most recent push to #442, results can be generated by anyone. Note that it is still probably better to wait until WIP status is resolved so the entire process is more friendly and error-less.

**Comment by adamdbrw** [comment]
Document that was presented during the Tooling WG call:
[Performance_findings.pdf](https://github.com/ros2/rosbag2/files/4805848/Performance_findings.pdf)

**Comment by adamdbrw** [comment]
@emersonknapp do you have plans to schedule the breakout session for rosbag2 performance soon?

**Comment by emersonknapp** [comment]
I've made the post to schedule the meeting, let me know if that's all ok. https://discourse.ros.org/t/tooling-wg-breakout-session-rosbag2-performance/15067 

Also, we will start taking a look at the code on 442

**Comment by adamdbrw** [comment]
The document that was presented during the breakout session: 
[ROS2_Tooling_Breakout.pdf](https://github.com/ros2/rosbag2/files/4904436/ROS2_Tooling_Breakout.pdf)

Note: I will update this document with some additional information and used memory readings next week (a minor update).

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/tooling-wg-breakout-session-rosbag2-performance/15067/10

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-07-16/15468/1

**Comment by emersonknapp** [comment]
@adamdbrw is this all finished? It looks like the listed issues are all checked off.

**Comment by adamdbrw** [comment]
Indeed - I am closing this

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/fast-forward-merging-rosbag2-master-api-to-foxy/18927/1
